### PR TITLE
DB_HW_Political_Campaign

### PR DESCRIPTION
**Pull request by miloszczapla**

### CODE REVIEW

**Review by irinakuzmina — CHANGES_REQUESTED** [review]
Hi Milosz, thank you for you work. Most of task requirements are fulfilled. Good job! Please find below minor comments:
1. Candidates and Voters tables are not in 3NF (as required by task) in the part of Address field. Even 1stNF requires atomic values in fields. Additionally, having address in one line causing multiple problems - parsing the data, validating the address, ets. please take a look at this material:  https://vertabelo.com/blog/address-in-database-model/ and https://misterivanlima.com/what-is-normalization-in-rdbms-with-examplesand, review materials on normalization and  attend q&a session, these topics should be reviewed there.
2. Schema file name is not fully as per requirements.
Please update your HW as per the comment and pass for the review again.

**Comment by miloszczapla** [comment]
Thx for comments and articles about 3rd Normal form - for me it is part of database topis that I struggel the most,

**Review by irinakuzmina — APPROVED** [review]
Hi Milosz, task is approved and can be merged.

**Comment by irinakuzmina** [comment]
@miloszczapla , please send the link to pr in **Learn** again, so that I could mark this task there.

**Comment by miloszczapla** [comment]
done :)

**Pull request merged**
