### PR TITLE
SQL_SELECT_HW

### PR DESCRIPTION
**Pull request by miloszczapla**

### CODE REVIEW

**Review by irinakuzmina — CHANGES_REQUESTED** [review]
Hi Milosz, thank you for the HW. Please find below comments to improve:
General: 
- Please review coding standards given in Introduction part(ON clauses should be on the same line with JOIN table, every column on a new line in select part, use uppercase letters for all SQL keywords and everything else in lowercase, ';' in the end of query, etc.). You can try sql online formatter. 
- Please add comments why you chose a particular way to solve each tasks. - this task requirement is almost 5not done. 
Following all tasks requirement, adding detailed comments  to the queries, following coding standards - always improves your score for the HW.

task 1.1 - "All animation movies" - this requirement is not considered in the query, hence the results are not correct. While doing this do not miss UPPER/LOWER in filters. SELECT * - is not a good practice, additionally only movies were required to be retrieved.
task 1.3 - "movies (released since 2015)" - this requirement is not considered in the query, hence the results are not correct.
task 1.4 and 1.5 - please add UPPER/LOWER in filters.
task 1.5 - DISTINC is missed so film titles are duplicated in results.
task 2.1 - revenue is calculated not correctly, please check this.
task 2.2 - grouping should be done by film_id, as titles in theory could duplicate.
task 3 - group by release_year should be removed to get correct results. Additionally, the results should be limited to the 'a longer period' as per task. It is not required to show all actors.

Please update your HW as per the comment and pass for the review again.

**Comment by miloszczapla** [comment]
Hi, I upload changes 😁

**Review by irinakuzmina — CHANGES_REQUESTED** [review]
Hi Milosz, thank you for updates, HW is improved. Here are still some comments to fix:

task 1.2 - the query stopped working after format changes, please check it.
task 1.3 - 'since 2015': usually 'since' means including the year.
task 2.1 - the query does not work and returns the error: "SQL Error [42803]: ERROR: column "s2.store_id" must appear in the GROUP BY clause or be used in an aggregate function"
Inventory and Rental tables are not required to solve this task. As an option a subquery can be used to identify the top three employees with the highest revenue totals in 2017, then join the staff table to add their store information.
task 2.2 - Please be aware that using FETCH FIRST ... ROWS WITH TIES instead of LIMIT helps to retrieve all rows that have the same value as the last row.

Please update your HW as per the comment and pass for the review again.

**Review by irinakuzmina — APPROVED** [review]
Hi Milosz, thanks for improvements.
Task is approved and can be merged.
Please note:
1. task 1.2 please note that appropriate date format is '2017-03-01', it influences the result.
2. Grade in Learn is calculated based on the quality of the first HW version.


Task is approved and can be merged.

**Pull request merged**
